# pyproject_setuptools.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Pyneapple"
version = "0.7.1"
description = "Pyneapple is an advanced tool for analysing multi-exponential signal data in MR DWI images."
readme = "README.md"
authors = [{ name = "Thomas Thiel", email = "thomas.thiel@hhu.de" }, { name = "Jonas Jasse" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = [
    "black>=23.3.0",
    "matplotlib>=3.7.0",
    "nibabel>=5.0.1",
    "numpy>=1.24",
    "Pillow>=10.2.0",
    "PyQt6>=6.4.2",
    "scipy>=1.10.1",
    "imantics>=0.1.12",
    "pytest>=7.4.2",
    "XlsxWriter~=3.1.5",
    "pandas~=2.1.3",
    "opencv-python~=4.8.0.76",
    "tqdm~=4.66.2",
    "parallelbar",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/darksim33/Pyneapple/"

[project.scripts]
PyneappleScript = "pyneapple.fit.PyNeapple_multi_script:run"
PyneappleUI_console = "pyneapple.ui.pyneapple_ui:run"

[project.gui-scripts]
PyneappleUI = "pyneapple.ui.pyneapple_ui:run"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyneapple*"]


[tool.bumpver]
#current_version = "2024.1001-alpha"
#version_pattern = "YYYY.BUILD[-TAG]"
current_version = "0.7.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]
"README.md" = [
    "{version}",
    "{pep440_version}",
]
"pyneapple/__init__.py" = ["{version}"]

