[tool.poetry]
name = "Pyneapple"
version = "0.8.3"
description = "Pyneapple is an advanced tool for analysing multi-exponential signal data in MR DWI images."
authors = ["Thomas Thiel <thomas.thiel@hhu.de>", "Jonas Jasse, <jonas.jasse@hhu.de>"]
maintainers = ["Jonas Jasse <jonas.jasse@hhu.de>"]
readme = "README.md"
license= "GPL-3.0-or-later"
homepage = "https://github.com/darksim33/Pyneapple/"
repository = "https://github.com/darksim33/Pyneapple/"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
packages = [
    { include = "pyneapple", from = "src" }
]
include = [
    "src/pyneapple/resources/fitting/*.json",
    "src/pyneapple/resources/images/*.png",
    "src/pyneapple/resources/images/*.ico"
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24"
nibabel = "^5.0.1"
matplotlib = "^3.7.0"
Pillow = "^10.2.0"
scipy = "^1.10.1"
imantics = "^0.1.12"
opencv-python = "^4.8.0.76"
pandas = "^2.1.3"
XlsxWriter = "^3.1.5"
tqdm = "^4.66.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
pytest = "^8.1.1"
pytest-order = "^1.2.1"

[tool.poetry.group.ui.dependencies]
PyQt6 = "^6.4.2"
parallelbar = "^2.4"

[tool.poetry.scripts]
PyneappleScript = "pyneapple.fit.PyNeapple_multi_script:run"
PyneappleUI = "pyneapple.ui.pyneapple_ui:run"
#PyneappleUI_console = "pyneapple.ui.pyneapple_ui:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
